Repository pagopa/pagopa-api-config, pull requests merged in 2022-11, with the labels that each got.

#153 [PCFG-298] Add force upload to ICA
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
Labels: enhancement

#154 Pcfg 298 caricamento forzato ica
  openapi/generate_openapi_and_swagger.sh
  openapi/swagger.json
Labels: ignore-for-release

#155 [PCFG-303] PSP code validation
  .github/workflows/update_openapi.yml
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/config/ResponseValidator.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ServicesController.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/PaymentServiceProvider.java
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/PspControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/PspServiceTest.java
  src/test/resources/file/ica_valid.xml
  src/test/resources/response/update_psp_ok.json
Labels: bug

#158 feat: [PCFG-314] Added target fields
  database/sql/V13__ALTER_STAZIONI.sql
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/get_station_ok1.json
  src/test/resources/response/update_station_ok.json
Labels: enhancement

#157 Massive Ica implementation
  .gitignore
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/config/ResponseValidator.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/MassiveCheck.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/CommonUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
  src/test/resources/file/massiveIca.zip
Labels: enhancement

#162 feat: [PCFG-327] X-Warning
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/config/ResponseValidator.java
  src/main/java/it/pagopa/pagopa/apiconfig/config/SwaggerConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/Constants.java
Labels: bug

#161 PCFG-321 creating massive ICAs upload
  .github/workflows/update_openapi.yml
  api-test/ApiConfig.postman_collection.json
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
  src/main/resources/application-docker.properties
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
  src/test/resources/application.properties
  src/test/resources/file/massiveIcaValid.zip
Labels: enhancement

#163 Updating properties values in d, u, p
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/resources/application-azure-d.properties
  src/main/resources/application-azure-p.properties
  src/main/resources/application-azure-t.properties
  src/main/resources/application-azure-u.properties
Labels: bug
