Repository pagopa/pagopa-api-config, pull requests merged in 2022-05, with the labels that each got.

#93 [PCFG-172] Creditor institution list of a station
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
  src/test/resources/response/get_station_creditorinstitutions_ok.json
Labels: enhancement

#94 [PCFG-170] Massive loading CI-Station
  api-test/ApiConfig.postman_collection.json
  api-test/utils/formData-k6-dep.js
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/controller/MassiveLoadingController.java
  src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/massiveloading/CreditorInstitutionStation.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/CreditorInstitutionStationVerifier.java
  src/main/resources/application-local.properties
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/MassiveLoadingControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepositoryTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceCollTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/util/CreditorInstitutionStationVerifierTest.java
  src/test/resources/file/ci_station_ko_1.csv
  src/test/resources/file/ci_station_ok.csv
  src/test/resources/response/get_station_ok1.json
  src/test/resources/response/update_station_ok.json
Labels: enhancement

#95 [PCFG-206] Creditor institution - station details
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/config/MappingsConfiguration.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaStazionePaToStationCreditorInstitution.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationCreditorInstitution.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationCreditorInstitutions.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
  src/test/resources/response/get_station_creditorinstitutions_ok.json
Labels: enhancement

#97 [PCFG-171] Export CSV Ec-Station
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/CommonUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
Labels: enhancement

#98 [PCFG-213] CI address
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCreditorInstitutionDetailsToPa.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionAddress.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionDetails.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
  src/test/resources/response/update_creditorinstitution_ok.json
Labels: enhancement

#100 [PCFG-184] implemented massive migration
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/MassiveLoadingController.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CsvMassiveMigration.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/CreditorInstitutionStationVerifier.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/controller/MassiveLoadingControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
  src/test/resources/file/ci_station_ok.csv
  src/test/resources/file/massive_migration.csv
Labels: enhancement

#107 fix swagger
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi.json
  openapi/swagger.json
Labels: bug

#108 [PCFG-229] Removed null fields
  .github/workflows/check_metadata_pr.yml
  .github/workflows/deploy.yml
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationCreditorInstitution.java
Labels: bug

#109 [PCFG-221] BugFix unique application/segregation code
  .github/workflows/check_metadata_pr.yml
  .github/workflows/update_infra.yml
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/CreditorInstitutionStationVerifier.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
Labels: bug

#111 [PCFG-231] ec station
  api-test/ApiConfig.postman_collection.json
  load-test/helpers/station_helper.js
  load-test/station.js
  src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
Labels: enhancement

#110 [PCFG-216] Update Swagger
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
Labels: ignore-for-release

#112 [PCFG-233] Fix CSV Station
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
Labels: bug

#117 [PCFG-214] Find creditor institution list by IBAN
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/IbanController.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionList.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/IbanValidiPerPaRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/IbanControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
  src/test/resources/response/get_creditorinstitutions_by_iban_1.json
  src/test/resources/response/get_creditorinstitutions_by_iban_2.json
Labels: enhancement

#118 Changed method name
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/IbanController.java
Labels: bug
