Repository pagopa/pagopa-api-config, pull requests merged in 2022-06, with the labels that each got.

#122 [PCFG-200] Export PSP list of a Channel
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ChannelsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/ChannelsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
Labels: enhancement

#121 [PCFG-230] removed file hash md5
  .devops/deploy-pipelines.yml
  database/sql/V3__IBAN.sql
  src/main/java/it/pagopa/pagopa/apiconfig/entity/BinaryFile.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CounterpartService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
Labels: bug

#125 fix: openapi & swagger
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/Service.java
Labels: bug, ignore-for-release

#126 [PCFG-239] Fix Protocol
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertChannelDetailsToCanali.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Protocol.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/create_station_ok.json
Labels: bug

#124 [PCFG-243] `FLAG_REPO_COMMISSIONE_CARICO_PA` default value
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaymentServiceProviderDetailsToPsp.java
Labels: bug

#127 [PCFG-247] Encondings check
  src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Broker.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/EncodingsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
Labels: bug

#129 [PCFG-256] Rollback Hash file
  database/sql/V3__IBAN.sql
  src/main/java/it/pagopa/pagopa/apiconfig/entity/BinaryFile.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CounterpartService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
Labels: bug
