Repository pagopa/pagopa-api-config, pull requests merged in 2023-06, with the labels that each got.

#218 [PAGOPA-989] Update IBAN API
  src/main/java/it/gov/pagopa/apiconfig/core/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertIbanAttributeMasterToIbanLabel.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement, size/large, minor

#216 feat: Add DELETE API IBAN [PAGOPA-988]
  src/main/java/it/gov/pagopa/apiconfig/core/controller/CreditorInstitutionsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement, size/small, minor

#224 [PAGOPA-1003] update performance test including IBAN handle tests
  load-test/helpers/iban_helper.js
  load-test/ibans.js
Labels: ignore-for-release, size/small

#222 [PAGOPA-1020] add due date to API: updated API and JUNIT test
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/IbanEnhanced.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/ChannelsService.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/resources/response/get_creditorinstitution_ibans_enhanced.json
Labels: enhancement, size/small, minor

#220 feat: Add check postal IBAN [PAGOPA-1018]
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application-pg-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, size/small, on hold, patch

#227 Pagopa 1035 api adjustment
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement, minor

#226 Pagopa 1011 creazione schedule per lettura table e aggiornamento file xml
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/config/SchedulerConfig.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/scheduler/SchedulerIca.java
  src/main/java/it/gov/pagopa/apiconfig/core/scheduler/entity/CreditorInstitutionIcaFile.java
  src/main/java/it/gov/pagopa/apiconfig/core/scheduler/storage/AzureStorageInteraction.java
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application-pg-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/scheduler/SchedulerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/scheduler/storage/AzureStorageInteractionTest.java
  src/test/resources/application.properties
Labels: enhancement, size/large, minor

#230 [PAGOPA-956] removed unused fields
  api-test/ApiConfig.postman_collection.json
  load-test/helpers/psps_helper.js
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertBrokerPspDetailsToIntermediariPsp.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertChannelDetailsToCanali.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCreditorInstitutionDetailsToPa.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCreditorInstitutionStationPostToPaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertPaymentServiceProviderDetailsToPsp.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertPspToPaymentServiceProviderDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/psp/PaymentServiceProviderDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/ChannelsService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/create_psp_ok.json
  src/test/resources/response/get_paymentserviceprovider_ok.json
  src/test/resources/response/update_psp_ok.json
Labels: enhancement, size/small, minor

#228 Pagopa 867 analisi export enti associati astazione ko
  .github/workflows/release_deploy.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/apiconfig/core/config/CacheConfig.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/ChannelsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/psp/CdiXml.java
  src/main/resources/application-h2.properties
  src/main/resources/application.properties
Labels: bug, size/large
