Repository pagopa/pagopa-api-config, pull requests merged in 2023-02, with the labels that each got.

#181 feat: [PAGOPA-630] Added 'primitive version' field for Channel and Station
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/entity/CanaliNodo.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertChannelDetailsToCanali.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/create_channel_ok.json
  src/test/resources/response/create_station_ok.json
  src/test/resources/response/get_channel_ok1.json
  src/test/resources/response/get_station_ok1.json
  src/test/resources/response/update_channel_ok.json
  src/test/resources/response/update_station_ok.json
Labels: enhancement

#180 [PAGOPA-633] abi cdi: added ABI in CDI object
  src/main/java/it/pagopa/pagopa/apiconfig/cosmos/container/CdiCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
Labels: bug

#179 Add Transactional
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/repository/TipiVersamentoRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
Labels: bug

#182 [PAGOPA-669] Get PSP by broker code
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Psp.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/CanaleTipoVersamentoRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/CanaliRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PspRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/BrokersPspService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/BrokersPspServiceTest.java
  src/test/resources/response/get_psp_brokerpsp.json
Labels: enhancement

#184 Cache
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/controller/CacheController.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Cache.java
  src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/configuration/Cache.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/configuration/CacheVersions.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/CacheRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CacheService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/CacheControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CacheServiceTest.java
Labels: enhancement

#185 PAGOPA-685 fixing regex and h2 sql files
  src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
Labels: bug

#189 Fix Aux Digit
  .gitignore
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionStationEdit.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
  src/test/resources/response/create_creditorinstitution_ok_2.json
Labels: bug, size/large
