Repository pagopa/pagopa-api-config, pull requests merged in 2023-07, with the labels that each got.

#231 feat: [PAGOPA-1066] update iban crud
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement, size/large, minor

#232 [PAGOPA-1012] feat: searching stations by broker name
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationsService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationsControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationsServiceTest.java
Labels: enhancement, size/small, patch

#234 fix: Bump vers
  .gitignore
  pom.xml
Labels: size/small

#236 fix: Bump version for sprint closure
  pom.xml
Labels: size/small, skip

#240 [PAGOPA-1087] fix: removing language checks on CDI upload
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/service/CdiService.java
  src/test/resources/file/cdi_not_valid_1.xml
Labels: bug, size/small, patch

#241 feat: Update IBAN Service for Encoding handling [PAGOPA-1014]
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/IbanEnhanced.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/scheduler/SchedulerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: patch

#237 fix: Timeout connection hikari pool
  .devops/aks-deploy-pipelines.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release_deploy.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/00_locals.tf
  .identity/00_variables.tf
  .identity/01_data.tf
  .identity/02_application_action.tf
  .identity/02_application_action_auth.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_outputs.tf
  .identity/99_variables.tf
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/resources/application.properties
Labels: bug, size/large, patch

#238 Pagopa 897 int test nuove api gestione iban
  .github/workflows/integration_test.yml
  integration-test/README.md
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/Iban.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/builder/buildIban.js
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/logic/ibanLogic.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/yarn.lock
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement, size/large, skip

#243 [PAGOPA-1076] Deleting unused NEW_PASSWORD field
  database/sql/V2__PA.sql
  database/sql/V6__CANALI.sql
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertChannelDetailsToCanali.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertStationDetailsToStazioni.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertStazioniToStationDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/StationDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/psp/ChannelDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/CdiService.java
  src/main/java/it/gov/pagopa/apiconfig/core/util/AFMUtilsAsyncTask.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/get_channel_ok1.json
  src/test/resources/response/get_station_ok1.json
  src/test/resources/response/update_station_ok.json
Labels: bug, size/large, patch

#244 [PAGOPA-1119] fix: Add hikari test query connection
  src/main/resources/application.properties
Labels: bug, size/small, patch

#245 fix: HEALTHCHECK_QUERY ora
  src/main/resources/application.properties
Labels: patch
