Repository pagopa/pagopa-api-config, pull requests merged in 2023-09, with the labels that each got.

#239 feat: adding python scripts for iban population PAGOPA-985
  scripts/utils/pythonExportIban/README.md
  scripts/utils/pythonExportIban/exporterIbanMasterToCsv.py
  scripts/utils/pythonExportIban/exporterIbanToCsv.py
  scripts/utils/pythonExportIban/exporterViewToCsv.py
  scripts/utils/pythonExportIban/exportingIbanMastertoDB.py
  scripts/utils/pythonExportIban/exportingIbanToDB.py
  scripts/utils/pythonExportIban/populate_tables.sh
  scripts/utils/pythonExportIban/requirements.md
  scripts/utils/pythonExportIban/rollbackFiles/README.md
  scripts/utils/pythonExportIban/rollbackFiles/deleteAll.py
  scripts/utils/pythonExportIban/rollbackFiles/rollback_iban.sh
Labels: enhancement, size/small, skip

#253 [PAGOPA-1228] new jdbc string
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/HomeController.java
  src/main/resources/logback-spring.xml
Labels: size/small, patch

#255 [PAGOPA-1259] fix: refresh of the cache
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_auth.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/service/RefreshService.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/RefreshServiceTest.java
Labels: size/small

#256 [PAGOPA-1053] Feedback on refresh of the configurazione
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/RefreshController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/RefreshService.java
Labels: size/small
