Repository pagopa/pagopa-api-config, pull requests merged in 2023-11, with the labels that each got.

#263 chore: Update update_infra.yml destination folder [PAGOPA-1325]
  .github/workflows/update_infra.yml
Labels: size/small

#264 Pagopa 1334 sviluppo iban modifica gestione due date e descrizione
  scripts/utils/pythonExportIban/exporterIbanMasterToCsv.py
  scripts/utils/pythonExportIban/exporterIbanToCsv.py
  scripts/utils/pythonExportIban/exportingIbanAttributesToDB.py
  scripts/utils/pythonExportIban/exportingIbanMastertoDB.py
  scripts/utils/pythonExportIban/exportingIbanToDB.py
  scripts/utils/pythonExportIban/populate_tables.sh
Labels: enhancement, size/small

#266 update starter
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertChannelDetailsToCanali.java
Labels: size/small

#265 Pagopa 1329 sviluppo recupero iban cup e aca
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/h2/data-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/resources/application.properties
Labels: enhancement

#273 [PASELC-595] feat: added counter for total elements on PageInfo
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/model/PageInfo.java
  src/main/java/it/gov/pagopa/apiconfig/core/util/CommonUtil.java
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/get_brokers_ok1.json
  src/test/resources/response/get_brokerspsp_ok1.json
  src/test/resources/response/get_cdis_ok1.json
  src/test/resources/response/get_channelsPSP_ok.json
  src/test/resources/response/get_channels_ok1.json
  src/test/resources/response/get_counterparttables_ok.json
  src/test/resources/response/get_creditorinstitutions_empty.json
  src/test/resources/response/get_creditorinstitutions_ok1.json
  src/test/resources/response/get_creditorinstitutions_ok2.json
  src/test/resources/response/get_creditorinstitutionserviceview_ok.json
  src/test/resources/response/get_icas_ok.json
  src/test/resources/response/get_paymentserviceproviders_ok.json
  src/test/resources/response/get_paymentserviceprovidersview_ok.json
  src/test/resources/response/get_psp_brokerpsp.json
  src/test/resources/response/get_services_ok1.json
  src/test/resources/response/get_services_ok2.json
  src/test/resources/response/get_station_creditorinstitutions_ok.json
  src/test/resources/response/get_stations_ok1.json
Labels: enhancement, size/small
