Repository pagopa/pagopa-api-config, pull requests merged in 2023-12, with the labels that each got.

#277 feat: fix orphan iban
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
Labels: bug, size/small

#276 chore: Pagopa 1370 sviluppo script conversione ica nuovo tracciato
  scripts/utils/pythonIcaIbanConverter/deleteIbans.py
  scripts/utils/pythonIcaIbanConverter/getCredInstFiscalCodes.py
  scripts/utils/pythonIcaIbanConverter/icaIbanConverter.py
Labels: size/small

#278 [PASELC-634] feat: IBAN label Stand-In management and other fixes
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Labels: enhancement

#279 Fix check on IBAN validity and due dates
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/java/it/gov/pagopa/apiconfig/core/util/CommonUtil.java
Labels: bug
