Repository pagopa/pagopa-api-config, pull requests merged in 2023-03, with the labels that each got.

#191 [PAGOPA-666] Pagination of GET psp by channel
  api-test/ApiConfig.postman_collection.json
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ChannelsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionStationEdit.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelPsp.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelPspList.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PspRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/ChannelsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
  src/test/resources/response/get_channelsPSP_ok.json
Labels: enhancement, size/large, minor

#193 [PAGOPA-798] Fix: station-creditor institution relation
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
Labels: bug

#195 Fix refresh config
  .github/workflows/self_hosted.yml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/config/LoggingAspect.java
  src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannel.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/RefreshService.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/RefreshServiceTest.java
Labels: bug, size/small, patch

#192 [PAGOPA-790] Multiple target endpoints
  database/sql/V15__ALTER_STAZIONI.sql
  database/sql/V17__ALTER_CANALI.sql
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Canali.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertChannelDetailsToCanali.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
  src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/get_channel_ok1.json
  src/test/resources/response/get_station_ok1.json
  src/test/resources/response/update_station_ok.json
Labels: size/large, minor

#198 fix
  .github/workflows/update_infra.yml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/resources/application-h2.properties
Labels: ignore-for-release, size/small, skip

#194 [PAGOPA-731] AFM Cosmos
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/ApiConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/config/CosmosDBConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
  src/main/java/it/pagopa/pagopa/apiconfig/cosmos/container/PaymentTypesCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/cosmos/repository/CdiCosmosRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/cosmos/repository/PaymentTypesCosmosRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/BinaryFile.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Cache.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/CanaleTipoVersamento.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/CdiMasterValid.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/PaStazionePa.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/ServiceAmountCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/afm/CdiCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/afm/CdiDetailCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/afm/PaymentTypesCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/CdiMasterValidRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ConfigurationService.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMMarketplaceClient.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsAsyncTask.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsClient.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/Constants.java
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application-pg-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
  src/test/java/it/pagopa/pagopa/apiconfig/config/MockitoConfig.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/CdiControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CdiServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ConfigurationServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsAsyncTaskTest.java
  src/test/resources/application.properties
Labels: bug, size/large, minor

#203 [PAGOPA 667] add filter to psp
  .devops/code-review-pipelines.yml
  src/main/java/it/pagopa/pagopa/apiconfig/ApiConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/config/OpenApiConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ChannelsController.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
  src/main/java/it/pagopa/pagopa/apiconfig/entity/Psp.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/afm/CdiCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/model/afm/CdiDetailCosmos.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/CdiMasterValidRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/repository/PspRepository.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
  src/main/java/it/pagopa/pagopa/apiconfig/service/ConfigurationService.java
  src/main/java/it/pagopa/pagopa/apiconfig/specification/PspSpecification.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMMarketplaceClient.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsAsyncTask.java
  src/main/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsClient.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/pagopa/pagopa/apiconfig/controller/CdiControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/controller/ChannelsControllerTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/CdiServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/ConfigurationServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/service/PspServiceTest.java
  src/test/java/it/pagopa/pagopa/apiconfig/util/AFMUtilsAsyncTaskTest.java
Labels: enhancement, size/large, minor

#200 [PAGOPA-681] Opex
  .github/workflows/create_dashboard.yaml
  .identity/.terraform.lock.hcl
  .identity/00_locals.tf
  .identity/00_main.tf.ci
  .identity/00_variables.tf
  .identity/01_data.tf
  .identity/02_application_action.tf
  .identity/02_application_action_auth.tf
  .identity/02_application_master.tf
  .identity/02_application_master_auth.tf
  .identity/02_application_pullrequest.tf
  .identity/02_application_pullrequest_auth.tf
  .identity/03_github_environment.tf
  .identity/terraform.sh
  .opex/auth/env/prod/backend.ini
  .opex/auth/env/prod/backend.tfvars
  .opex/auth/env/prod/config.yaml
  .opex/auth/env/prod/terraform.tfvars
  .opex/node/env/prod/backend.ini
  .opex/node/env/prod/backend.tfvars
  .opex/node/env/prod/config.yaml
  .opex/node/env/prod/terraform.tfvars
  .opex/product/env/dev/backend.ini
  .opex/product/env/dev/backend.tfvars
  .opex/product/env/dev/config.yaml
  .opex/product/env/prod/backend.tfvars
  .opex/product/env/uat/backend.ini
  .opex/product/env/uat/backend.tfvars
  .opex/product/env/uat/config.yaml
  .opex/product/env/uat/terraform.tfvars
  context.json
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi_auth.json
  pom.xml
  src/main/java/it/pagopa/pagopa/apiconfig/config/OpenApiConfig.java
  src/main/java/it/pagopa/pagopa/apiconfig/controller/HomeController.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: size/large, skip
