Repository pagopa/pagopa-api-config, pull requests merged in 2024-05, with the labels that each got.

#267 chore: Import script iban
  scripts/utils/pythonExportIban/exporterIbanMasterToCsv.py
  scripts/utils/pythonExportIban/exportingIbanMastertoDB.py
  scripts/utils/pythonExportIban/populate_tables.sh
  scripts/utils/pythonExportIban/rollbackFiles/rollback.py
Labels: bug, size/small

#290 add - initial cbill import script
  scripts/utils/cbill/README.md
  scripts/utils/cbill/import-cbill.py
Labels: size/small

#296 PAGOPA-1754 fix canali nodo creation
  openapi/openapi.json
  scripts/utils/pythonDeleteOrphansCanaliNodo/deleteOrphansCanaliNodo.py
  src/main/java/it/gov/pagopa/apiconfig/core/service/ChannelsService.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
Labels: bug, size/small

#297 PAGOPA-1769 new page logic for iban
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/IbansEnhanced.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/resources/response/get_creditorinstitution_ibans_enhanced.json
Labels: enhancement, size/large

#298 PAGOPA-1769 add cbill code massive loading feature
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/CreditorInstitutionsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/massiveloading/CbillMassiveLoadCsv.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/CreditorInstitutionsService.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/core/controller/CreditorInstitutionsControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/CreditorInstitutionsServiceTest.java
  src/test/resources/file/massiveCbillValid_Insert.csv
Labels: size/large

#301 Pagopa 1770 api cfg pag canali e stazioni
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/service/ChannelsService.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationsService.java
Labels: bug, size/small

#302 ci(helm): Update proxy body size value
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small
