Repository pagopa/pagopa-api-config, pull requests merged in 2024-08, with the labels that each got.

#317 fix: Date format
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/util/Constants.java
Labels: size/small, patch

#318 fix: bump api config starter version
  pom.xml
Labels: size/small

#319 fix: massive ci upload from csv aca and standIn management
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/model/massiveloading/CreditorInstitutionStation.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/MassiveLoadingService.java
  src/test/resources/file/ci_station_ko_1.csv
  src/test/resources/file/ci_station_ok.csv
  src/test/resources/file/ci_station_ok_postman.csv
Labels: bug, size/small, patch
