Repository pagopa/pagopa-api-config, pull requests merged in 2024-07, with the labels that each got.

#306 [VAS-1146] feat: Added property "primitive_version" to Channel class
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCanaliToChannel.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/psp/Channel.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/psp/ChannelDetails.java
Labels: size/small, minor

#308 [VAS-1170] feat: Bump api-config-starter dependency
  pom.xml
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
Labels: size/small, minor

#309 [VAS-1171] feat: Add create maintenance API
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/gov/pagopa/apiconfig/core/repository/ExtendedStationMaintenanceRepository.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
  src/test/resources/response/get_channels_ok1.json
Labels: enhancement, size/large, minor

#310 [PPANTT-36] feat: Add update maintenance API
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/repository/PaStazionePaRepositoryTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
Labels: enhancement, size/large, minor

#307 [PAGOPA-1732] feat: Add property "aca" & "standIn" to CI-station relation
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCreditorInstitutionStationPostToPaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertPaStazionePaToCreditorInstitutionStation.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertPaStazionePaToStationCreditorInstitution.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/CreditorInstitutionStation.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/CreditorInstitutionStationEdit.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/StationCreditorInstitution.java
Labels: enhancement, size/small, minor

#312 [PPANTT-39] feat: Add list maintenance API
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/gov/pagopa/apiconfig/core/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertStationMaintenanceToStationMaintenanceResource.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/StationMaintenanceListResource.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
Labels: enhancement, minor

#314 [PPANTT-45] feat: Add delete maintenance API
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
Labels: enhancement, size/small, minor

#311 [PPANTT-44] feat: add get maintenance detail api
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/repository/ExtendedStationMaintenanceRepository.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
Labels: size/small, minor

#315 fix: Update openapi for station maintenance APIs
  openapi/openapi.json
  openapi/swagger.json
Labels: size/large, skip

#316 fix: Maintenance API
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/repository/ExtendedStationMaintenanceRepository.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
Labels: patch
