Repository pagopa/pagopa-api-config, pull requests merged in 2024-01, with the labels that each got.

#275 chore: Pagopa 1378 sviluppo caricamento massivo iban da csv
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertIbansMassLoadCsvToIbanMaster.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/massiveloading/IbanMassLoadCsv.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/massiveloading/IbansMassLoadCsv.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/resources/h2/data-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/resources/file/massiveIbansInvalid_NotRequiredValue.csv
  src/test/resources/file/massiveIbansInvalid_NotWellFormed.csv
  src/test/resources/file/massiveIbansValid_Bad.csv
  src/test/resources/file/massiveIbansValid_BadOperationValue.csv
  src/test/resources/file/massiveIbansValid_Insert.csv
  src/test/resources/file/massiveIbansValid_Update_Delete.csv
  src/test/resources/file/massiveIbansValid_existingIban_Insert.csv
Labels: size/large

#281 feat: minor bug-fixing on IBAN update and added new filter for stations
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationsService.java
  src/main/java/it/gov/pagopa/apiconfig/core/specification/PaStazionePaSpecification.java
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationsServiceTest.java
  src/test/java/it/gov/pagopa/apiconfig/core/specification/PaStazionePaSpecificationTest.java
Labels: enhancement, size/small

#282 feat: [PagoPA-1387]: integration test massive csv upload
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/Iban.massive.feature
  integration-test/src/step_definitions/support/iban.massive.js
  integration-test/src/step_definitions/support/logic/health_checks_logic.js
  integration-test/src/step_definitions/support/logic/ibanLogic.js
  integration-test/src/step_definitions/support/resources/BAD_delete.csv
  integration-test/src/step_definitions/support/resources/BAD_format.csv
  integration-test/src/step_definitions/support/resources/BAD_iban.csv
  integration-test/src/step_definitions/support/resources/BAD_insert.csv
  integration-test/src/step_definitions/support/resources/BAD_insert_postal_iban.csv
  integration-test/src/step_definitions/support/resources/BAD_update.csv
  integration-test/src/step_definitions/support/resources/delete.csv
  integration-test/src/step_definitions/support/resources/insert.csv
  integration-test/src/step_definitions/support/resources/mix.csv
  integration-test/src/step_definitions/support/resources/update.csv
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
Labels: enhancement, minor

#285 PAGOPA-1462 fixing fe swagger
  openapi/generate_openapi_and_swagger.sh
  openapi/openapi.json
  openapi/swagger.json
Labels: bug, size/small

#286 [PASELC-714] Added CBill code mapping
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/swagger.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertCreditorInstitutionDetailsToPa.java
  src/main/java/it/gov/pagopa/apiconfig/core/mapper/ConvertPaToCreditorInstitutionDetails.java
  src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/CreditorInstitutionDetails.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
  src/test/resources/response/create_creditorinstitution_ok.json
  src/test/resources/response/get_creditorinstitution_ok.json
  src/test/resources/response/update_creditorinstitution_ok.json
Labels: enhancement, size/small

#287 updating openapi and swagger
  openapi/openapi.json
  openapi/swagger.json
Labels: bug, size/small

#289 [PASELC-712] add new filterByCiNameOrCF parameter
  openapi/openapi.json
  openapi/swagger.json
  src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
  src/main/java/it/gov/pagopa/apiconfig/core/service/StationsService.java
  src/main/java/it/gov/pagopa/apiconfig/core/specification/PaStazionePaSpecification.java
  src/test/java/it/gov/pagopa/apiconfig/core/service/StationsServiceTest.java
Labels: enhancement, size/small
